
spring:
  application:
    name: paygateway
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console # Access at http://localhost:8080/h2-console
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect

# MySQL database configuration

#  datasource:
#    url: jdbc:mysql://localhost:3306/paymentgateway
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update  # Use "update", "create-drop", or "none" based on your need
#    show-sql: true  # Show SQL queries in the console


razorpay:
  api:
    key: rzp_test_GLAIBAfJGRg5lh
    secret: 6R5uN9geHXNwjz768zD5lymD
server:
  port: 8080
